services:
    postgres:
      image: 'postgres:latest'
      environment:
        - 'POSTGRES_DB=zafersdb'
        - 'POSTGRES_PASSWORD=secret'
        - 'POSTGRES_USER=myuser'
      ports:
        - '5432:5432'  